apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todoapp
  labels:
    app: mysql
    tier: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "mySecurePassword123!"  # փոխել production-ում
  MYSQL_DATABASE: "todos"
  MYSQL_USER: "todouser"
  MYSQL_PASSWORD: "todopass123!"  # փոխել production-ում